//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WodFurnitureKart.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManufacturer
    {
        public int ManufacturerId { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
    }
}
